server:
  port: 8081
  servlet:
    context-path: /employee-service

spring:
  application:
    name: onthick-employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/onthick_ktpm
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
    generate-ddl: true

